#if !canImport(ObjectiveC)
import XCTest

extension OffsetMetadataTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OffsetMetadataTests = [
        ("testInitNoRequest", testInitNoRequest),
        ("testInvalidPageInitNoRequest", testInvalidPageInitNoRequest),
        ("testMetadataLink", testMetadataLink),
        ("testMetadataLinks", testMetadataLinks),
        ("testNextAndPreviousLinksFirstPage", testNextAndPreviousLinksFirstPage),
        ("testNextAndPreviousLinksInvalidPage", testNextAndPreviousLinksInvalidPage),
        ("testNextAndPreviousLinksLastPage", testNextAndPreviousLinksLastPage),
        ("testNextAndPreviousLinksMiddlePage", testNextAndPreviousLinksMiddlePage),
        ("testPageZeroInitNoRequest", testPageZeroInitNoRequest),
        ("testZeroInitNoRequest", testZeroInitNoRequest),
        ("testZeroPerPageInitNoRequest", testZeroPerPageInitNoRequest),
    ]
}

extension OffsetPaginatableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OffsetPaginatableTests = [
        ("testPaginateNoTransformer", testPaginateNoTransformer),
        ("testPaginateNoTransformerInvalidPageSix", testPaginateNoTransformerInvalidPageSix),
        ("testPaginateNoTransformerPageFive", testPaginateNoTransformerPageFive),
        ("testPaginateNoTransformerPageFour", testPaginateNoTransformerPageFour),
        ("testPaginateNoTransformerPageThree", testPaginateNoTransformerPageThree),
        ("testPaginateNoTransformerPageTwo", testPaginateNoTransformerPageTwo),
        ("testPaginateParametersWithRequest", testPaginateParametersWithRequest),
        ("testPaginateWithRequest", testPaginateWithRequest),
        ("testPaginateWithTransformer", testPaginateWithTransformer),
    ]
}

extension OffsetPaginationDataSourceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OffsetPaginationDataSourceTests = [
        ("testDataSourcePaginate", testDataSourcePaginate),
    ]
}

extension OffsetPaginatorTransformTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OffsetPaginatorTransformTests = [
        ("testAsyncMap", testAsyncMap),
        ("testAsyncMapFuture", testAsyncMapFuture),
        ("testMap", testMap),
        ("testMapFuture", testMapFuture),
        ("testMapSingle", testMapSingle),
        ("testMapSingleFuture", testMapSingleFuture),
    ]
}

extension OffsetParametersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OffsetParametersTests = [
        ("testConfigAndEmptyQueryParameterInit", testConfigAndEmptyQueryParameterInit),
        ("testConfigAndInvalidQueryParameterInit", testConfigAndInvalidQueryParameterInit),
        ("testConfigAndQueryParameterInit", testConfigAndQueryParameterInit),
        ("testInit", testInit),
        ("testInitExtremeNegativePage", testInitExtremeNegativePage),
        ("testInitExtremeNegativePerPage", testInitExtremeNegativePerPage),
        ("testInitLessThanOnePerPage", testInitLessThanOnePerPage),
        ("testInitLessThanPageOne", testInitLessThanPageOne),
    ]
}

extension OffsetQueryParametersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OffsetQueryParametersTests = [
        ("testInit", testInit),
        ("testInitExtremeNegativePage", testInitExtremeNegativePage),
        ("testInitExtremeNegativePerPage", testInitExtremeNegativePerPage),
        ("testInitExtremePositivePage", testInitExtremePositivePage),
        ("testInitExtremePositivePerPage", testInitExtremePositivePerPage),
        ("testInitNegativePage", testInitNegativePage),
        ("testInitNegativePerPage", testInitNegativePerPage),
        ("testInitNilInput", testInitNilInput),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(OffsetMetadataTests.__allTests__OffsetMetadataTests),
        testCase(OffsetPaginatableTests.__allTests__OffsetPaginatableTests),
        testCase(OffsetPaginationDataSourceTests.__allTests__OffsetPaginationDataSourceTests),
        testCase(OffsetPaginatorTransformTests.__allTests__OffsetPaginatorTransformTests),
        testCase(OffsetParametersTests.__allTests__OffsetParametersTests),
        testCase(OffsetQueryParametersTests.__allTests__OffsetQueryParametersTests),
    ]
}
#endif
