#if !canImport(ObjectiveC)
import XCTest

extension OffsetMetaDataTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OffsetMetaDataTests = [
        ("testInit", testInit),
        ("testZeroInit", testZeroInit),
        ("testZeroPerPageInit", testZeroPerPageInit),
    ]
}

extension PaginatorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PaginatorTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(OffsetMetaDataTests.__allTests__OffsetMetaDataTests),
        testCase(PaginatorTests.__allTests__PaginatorTests),
    ]
}
#endif
