#if !canImport(ObjectiveC)
import XCTest

extension OffsetMetadataTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OffsetMetadataTests = [
        ("testInitNoRequest", testInitNoRequest),
        ("testInvalidPageInitNoRequest", testInvalidPageInitNoRequest),
        ("testMetadataLink", testMetadataLink),
        ("testMetadataLinks", testMetadataLinks),
        ("testNextAndPreviousLinksFirstPage", testNextAndPreviousLinksFirstPage),
        ("testNextAndPreviousLinksInvalidPage", testNextAndPreviousLinksInvalidPage),
        ("testNextAndPreviousLinksLastPage", testNextAndPreviousLinksLastPage),
        ("testNextAndPreviousLinksMiddlePage", testNextAndPreviousLinksMiddlePage),
        ("testPageZeroInitNoRequest", testPageZeroInitNoRequest),
        ("testZeroInitNoRequest", testZeroInitNoRequest),
        ("testZeroPerPageInitNoRequest", testZeroPerPageInitNoRequest),
    ]
}

extension OffsetParametersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OffsetParametersTests = [
        ("testConfigAndEmptyQueryParameterInit", testConfigAndEmptyQueryParameterInit),
        ("testConfigAndInvalidQueryParameterInit", testConfigAndInvalidQueryParameterInit),
        ("testConfigAndQueryParameterInit", testConfigAndQueryParameterInit),
        ("testInit", testInit),
        ("testInitExtremeNegativePage", testInitExtremeNegativePage),
        ("testInitExtremeNegativePerPage", testInitExtremeNegativePerPage),
        ("testInitLessThanOnePerPage", testInitLessThanOnePerPage),
        ("testInitLessThanPageOne", testInitLessThanPageOne),
    ]
}

extension OffsetQueryParametersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OffsetQueryParametersTests = [
        ("testInit", testInit),
        ("testInitExtremeNegativePage", testInitExtremeNegativePage),
        ("testInitExtremeNegativePerPage", testInitExtremeNegativePerPage),
        ("testInitExtremePositivePage", testInitExtremePositivePage),
        ("testInitExtremePositivePerPage", testInitExtremePositivePerPage),
        ("testInitNegativePage", testInitNegativePage),
        ("testInitNegativePerPage", testInitNegativePerPage),
        ("testInitNilInput", testInitNilInput),
    ]
}

extension PaginatorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PaginatorTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(OffsetMetadataTests.__allTests__OffsetMetadataTests),
        testCase(OffsetParametersTests.__allTests__OffsetParametersTests),
        testCase(OffsetQueryParametersTests.__allTests__OffsetQueryParametersTests),
        testCase(PaginatorTests.__allTests__PaginatorTests),
    ]
}
#endif
